
spring:
  rabbitmq:
    port: 5672
    host: localhost
server:
  port: 8882
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 
management:
  security:
    enabled: false
